{% set name = "beanie" %}
{% set version = "1.26.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/roman-right/beanie/archive/refs/tags/{{ version }}.tar.gz
  sha256: 47eff0a7ab319b0e429613a441cd4d68233e1b52844813c71bf0171f573ebb3b
  patches:

build:
  entry_points:
    - beanie = beanie.executors.migrate:migrations
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - flit-core
    - python >=3.7
  run:
    - click >=7
    - motor >=2.5,<4.0
    - pydantic >=1.10.0,<3
    - python >=3.7
    - toml
    - lazy-model >=0.2.0

test:
  imports:
    - beanie
  commands:
    - pip check
    - beanie --help
  requires:
    - pip

about:
  home: https://roman-right.github.io/beanie/
  dev_url: https://github.com/roman-right/beanie
  summary: Asynchronous Python ODM for MongoDB
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - awvwgk
